list:
  - name: ems
    bearer: "123456"
    ip:
      - "127.0.0.1"
      - "103.20.120.53"
  - name: snh
    bearer: "123457"
    ip:
      - "127.0.0.1"
      - "103.20.120.53"
  - name: kcmh
    bearer: "123458"
    ip:
      - "127.0.0.1"
      - "10.56.17.95"
      - "192.168.65.1"
    trusted_proxy:
      - "nginx"   # หรือใส่ subnet ของ nginx/docker เช่น "172.18.0.0/16"